import type { Project } from '@/types/project';

export const projects: Project[] = [
  {
    id: 'sumo-cars',
    number: '01',
    type: 'MULTIPLAYER GAME',
    title: 'Sumo Cars.io',
    subtitle: 'Multiplayer Arcade Territory Control Game',
    year: '2022 — Present',
    description:
      'An 8-player real-time multiplayer .io game where cars drift to paint territory and knock opponents off the arena. Features sumo-style knockback combat, two-tier boost mechanics, per-pixel territory scoring, and cross-platform play.',
    tech: ['Unity 3D', 'C#', 'Netcode for GameObjects', 'Cross-Platform'],
    highlights: [
      '8-player real-time multiplayer',
      'Territory painting via drift mechanics',
      'Per-pixel scoring with live leaderboards',
      'Zero material duplication for 8 unique player visuals',
    ],
    accent: 'var(--accent-cyan)',
    image: '/images/projects/sumo-cars-hero.jpg',
    video: '/videos/sumo-cars-gameplay.mp4',
    github: 'https://github.com/UJJWAL16895/',
    featured: true,
  },
  {
    id: 'driving-simulator',
    number: '02',
    type: 'SIMULATION GAME',
    title: '3D Driving Simulator',
    subtitle: 'Realistic Vehicle Physics Sandbox',
    year: '2023',
    description:
      'A realistic driving simulator with custom vehicle physics using Wheel Colliders and Rigidbodies, spline-based road networks, Cinemachine camera systems, and URP rendering with PBR textures and HDR skyboxes.',
    tech: ['Unity URP', 'C#', 'Cinemachine', 'Blender'],
    highlights: [
      'Custom suspension and torque distribution',
      'Spline-based highway generation',
      'Dynamic Cinemachine camera system',
      'PBR textures with HDR lighting',
    ],
    accent: 'var(--accent-purple)',
    image: '/CarSimulatorThumbnail.png',
    video: '/CarSimulator.mp4',
    featured: false,
  },
  {
    id: 'finvani',
    number: '03',
    type: 'ML / NLP',
    title: 'FinVani',
    subtitle: 'Real-Time Financial Sentiment Analysis for Indian MSMEs',
    year: '2024 — 2025',
    description:
      'A multilingual NLP platform analyzing financial sentiment across 22 Indian languages. Features real-time news scraping, MSME-centric scoring algorithms, and interactive dashboards for data-driven business decisions.',
    tech: ['Python', 'Hugging Face', 'FastAPI', 'NLTK', 'Spacy'],
    highlights: [
      '22 Indian languages supported',
      'Custom MSME impact scoring algorithm',
      'Real-time financial news pipeline',
      'Capstone project at LPU',
    ],
    accent: 'var(--accent-magenta)',
    image: '/Finvani Thumbnail.png',
    featured: false,
  },
  {
    id: 'theeducode',
    number: '04',
    type: 'ED-TECH PLATFORM',
    title: 'TheEducode',
    subtitle: 'Full-Stack Educational Platform with Secure Exams',
    year: '2025 — Present',
    description:
      'A comprehensive learning platform built during my internship at Eduniketan. Features role-based auth (Student/Teacher/Admin), secure examination environments with anti-cheat proctoring, interactive coding challenges with hidden test cases, and real-time analytics dashboards.',
    tech: ['Node.js', 'Express', 'Supabase', 'Firebase', 'JWT'],
    highlights: [
      'Multi-role architecture (Student/Teacher/Admin)',
      'Anti-cheat proctoring metadata tracking',
      'Dynamic coding evaluation with hidden test cases',
      '30% reduction in page load times',
    ],
    accent: 'var(--accent-green)',
    image: '/EducodeThumbnail.png',
    featured: true,
  },
  {
    id: 'endless-runner',
    number: '05',
    type: 'MOBILE GAME',
    title: 'Chaser',
    subtitle: 'High-Performance 3D Endless Runner',
    year: '2023',
    description:
      'A fast-paced 3D endless runner with procedurally generated obstacles, smooth controls, and optimized performance for mobile devices.',
    tech: ['Unity 3D', 'C#', 'Blender'],
    highlights: [
      'Procedural obstacle generation',
      'Smooth touch-based controls',
      'Performance-optimized for mobile',
    ],
    accent: 'var(--accent-orange)',
    image: '/Chaser Thumbnail.png',
    featured: false,
  },
  {
    id: 'speed-flappy',
    number: '06',
    type: 'MOBILE GAME',
    title: 'Speed',
    subtitle: 'Physics-Based 2D Arcade Game',
    year: '2023',
    description:
      'A physics-based 2D arcade game inspired by Flappy Bird, featuring precise collision detection, score tracking, and polished visual feedback.',
    tech: ['Unity 2D', 'C#'],
    highlights: [
      'Precise physics-based mechanics',
      'Score tracking system',
      'Polished visual feedback',
    ],
    accent: 'var(--accent-cyan)',
    image: '/Speed flappy bird.png',
    featured: false,
  },
  {
    id: 'route-optimization',
    number: '07',
    type: 'MACHINE LEARNING',
    title: 'Solid Waste Route Optimizer',
    subtitle: 'ML-Powered Vehicle Routing Problem Solver',
    year: '2025 — 2026',
    description:
      'An ML system solving the Vehicle Routing Problem for solid waste collection using K-Means clustering and heuristic models to minimize travel distance and fuel consumption from geospatial data.',
    tech: ['Python', 'Scikit-Learn', 'K-Means', 'Pandas', 'NumPy'],
    highlights: [
      'K-Means based route clustering',
      'Heuristic optimization algorithms',
      'Geospatial data processing',
      'Fuel consumption minimization',
    ],
    accent: 'var(--accent-purple)',
    image: '/Solid Waste thumbnail.png',
    video: '/SolidWaste.mp4',
    github: 'https://github.com/UJJWAL16895/route-optimization',
    featured: true,
  },
];
